### ISSUE TITLE
Introduce metrics about corrupted data [NOKR][tracker]

### ISSUE THREAD

**Issue by pacospace** [thoth-station/storages#1885]
As Thoth Data Engineer,
I want to discover if any data is corrupted in the database, showing the analysis on Grafana, receive alarms from Prometheus and take action on it.

Acceptance Criteria:
- [x] ~~Create Dockerfile for postgresql10.0-rhel + amcheck that can be deployed.~~
- [x] Create query on database in thoth-storages (https://github.com/thoth-station/storages/issues/1586, https://github.com/thoth-station/storages/issues/1405)
- [x] Create metrics in metrics-exporter (https://github.com/thoth-station/metrics-exporter/issues/408)
- [x] Create alarm on Prometheus.

References:
- https://docs.google.com/document/d/1onhwI_3GGLfmAtZ74WDij_03kCk3Fn4ZoU0iDxCJkq4/edit

**Comment by fridex** [comment]
https://github.com/thoth-station/metrics-exporter/issues/408

**Comment by pacospace** [comment]
> [thoth-station/metrics-exporter#408](https://github.com/thoth-station/metrics-exporter/issues/408)

I linked that issue in this card [tracker] as third point already, as first we need an image with Postgres and that extension `amcheck`, probably RPM, to be created.

**Comment by fridex** [comment]
> > [thoth-station/metrics-exporter#408](https://github.com/thoth-station/metrics-exporter/issues/408)
> 
> I linked that issue in this card [tracker] as third point already, as first we need an image with Postgres and that extension `amcheck`, probably RPM, to be created.

Not to maintain too many PG images, I think we could reuse the base image used in graph-backup-job.

CC @harshad16

**Comment by KPostOffice** [comment]
I don't have access to `access.redhat.com` so I'm having trouble getting the yum repositories that I need in order to build amcheck from source.

**Comment by pacospace** [comment]
@KPostOffice @goern

**Comment by KPostOffice** [comment]
postgres10 actually has this extension available. No need to use a community build. `amcheck_next10` adds functionality of the amcheck available in postgres 11+ to postgres 10 and there is another build to backport the functionality to postgres9.  It should be as easy as enabling the module and running the command that I described in the doc.

**Comment by pacospace** [comment]
This issue can be closed: https://gitlab.cee.redhat.com/data-hub/dh-monitoring/-/merge_requests/374
